/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bank.gui;

import com.bank.dominio.Banco;
import com.bank.servicios.GestionBanco;
import com.bank.servicios.GestionClientes;
import java.util.List;
import javax.swing.JOptionPane;

public class VentanaBanco extends javax.swing.JFrame {

    private Banco banco;
    private static final int ID_BANCO = 1;
    /**
     * Creates new form VentanaBanco
     */
    public VentanaBanco() {
        initComponents();
        iniciarBanco();
        if(banco != null){
             this.lbNombreBanco.setText(banco.getNombre());
             iniciarClientes();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNombreBanco = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        btnVerCuentasBanc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbNombreBanco.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbNombreBanco.setForeground(new java.awt.Color(51, 102, 0));
        lbNombreBanco.setText("Nombre Banco");

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaClientes);

        btnVerCuentasBanc.setText("Ver Cuentas Bancarias");
        btnVerCuentasBanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCuentasBancActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbNombreBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerCuentasBanc)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbNombreBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnVerCuentasBanc)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerCuentasBancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCuentasBancActionPerformed
        
        int row = tablaClientes.getSelectedRow();
        //si no ha seleccionado una fila devuelve -1
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Seleccione un cliente");
        }else{
            int idCliente =(Integer) (tablaClientes.getModel().getValueAt(row, 0)); //obtener valor colum 1
            System.out.println("id cliente " + idCliente);
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCuentasCliente(idCliente).setVisible(true);
            }
        });
        }
        
    }//GEN-LAST:event_btnVerCuentasBancActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBanco().setVisible(true);
            }
        });
    }
    
    
    
    
    private void iniciarBanco(){
        try {
            GestionBanco g = new GestionBanco();
            banco = g.getBancoPorId(ID_BANCO);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    
    
    
    
    private void iniciarClientes(){
        
        try {
            GestionClientes gc = new GestionClientes();
            List lista = gc.getClientesPorIdBanco(ID_BANCO);
            if(lista.isEmpty()){
               JOptionPane.showMessageDialog(this, "El banco no tiene clientes.");
               btnVerCuentasBanc.setEnabled(false);
            }else{
                //System.out.println(lista);
                tablaClientes.setModel(new ClientesDataModel(lista));
                btnVerCuentasBanc.setEnabled(true);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerCuentasBanc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNombreBanco;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables
}
